#define TAPPING_TERM 220
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define FLOW_TAP_TERM 150
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_RIGHT_ALT) }
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18